import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Ascend",
    short_name: "Ascend",
    description: "Point-of-sale and business management platform",
    start_url: "/terminal",
    display: "standalone",
    // Both were drifted brand values: #5D5FEF is the purple retired before the
    // blue that app/layout.tsx was still carrying, so an installed Ascend had
    // THREE different brand colours across its splash, its status bar and its
    // UI. These now match --color-canvas and --color-topbar-bg in globals.css.
    background_color: "#F6F7F8",
    theme_color: "#14181F",
    orientation: "any",
    // Generated by `scripts/generate-pwa-icons.mjs`. Both files were referenced
    // here but had never been committed, so every home-screen install fell back
    // to a browser-default icon.
    //
    // Each file is declared twice, once per purpose. The manifest spec allows
    // a space-separated `"any maskable"`, but Next's `MetadataRoute.Manifest`
    // types `purpose` as a single enum member and rejects it. Separate entries
    // are equivalent to the browser and keep the file type-checked.
    //
    // Both purposes matter: a maskable-only icon is padded and shrunk by
    // browsers that apply no mask, which is why such icons often look too
    // small in a tab or menu.
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    screenshots: [],
    categories: ["business", "finance", "productivity"],
    shortcuts: [
      {
        name: "New Sale",
        short_name: "Sale",
        url: "/terminal",
        description: "Open the POS terminal",
      },
      {
        name: "Orders",
        short_name: "Orders",
        url: "/orders",
        description: "View recent orders",
      },
    ],
  };
}
