/**
 * Generates the developer-facing business-pack matrix (FORWARD_PLAN.md,
 * Phase 3: "Add a developer-facing business-pack matrix generated from the
 * registry and test evidence.").
 *
 * Single source of truth: this reads the SAME registry objects the backend
 * uses at runtime (src/shared/moduleRegistry.ts, src/modules/settings/
 * service.ts) — nothing here is hand-maintained data. Re-run whenever the
 * registry changes; the output file is fully overwritten, never hand-edited.
 *
 * Usage: npm run business:matrix
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  MODULE_REGISTRY,
  BUSINESS_BUNDLES,
  GROUP_LABELS,
  CORE_MODULES,
} from "../src/shared/moduleRegistry.js";
import {
  BUSINESS_CAPABILITY_PROFILES,
  BUSINESS_SETUP_TASKS,
  MODULE_PERMISSIONS,
  MODULE_REPORTS,
} from "../src/modules/settings/service.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "../docs/architecture/BUSINESS_PACK_MATRIX.md");

function moduleStatus(key: string, defaultEnabled: boolean): string {
  const hasRoute = MODULE_REGISTRY.find((m) => m.key === key)?.route;
  if (CORE_MODULES.has(key)) return "Built and verified (core)";
  if (!defaultEnabled) return "Not in this pack";
  return hasRoute ? "Built but not verified" : "Partial (no dedicated page)";
}

function buildBusinessTypeSection(businessType: string): string {
  const bundle = BUSINESS_BUNDLES[businessType];
  if (!bundle) return "";
  const profile = BUSINESS_CAPABILITY_PROFILES[businessType] ?? BUSINESS_CAPABILITY_PROFILES["custom"]!;
  const setupTasks = BUSINESS_SETUP_TASKS[businessType] ?? [];
  const bundleModules = new Set(bundle.modules);
  const allRelevantKeys = [...new Set([...CORE_MODULES, ...bundle.modules])];
  const rows = allRelevantKeys
    .map((key) => MODULE_REGISTRY.find((m) => m.key === key))
    .filter((m): m is (typeof MODULE_REGISTRY)[number] => Boolean(m))
    .map((mod) => {
      const enabledByDefault = Boolean(mod.core) || bundleModules.has(mod.key);
      const status = moduleStatus(mod.key, enabledByDefault);
      const perms = MODULE_PERMISSIONS[mod.key]?.join(", ") ?? "—";
      const reports = MODULE_REPORTS[mod.key]?.join(", ") ?? "—";
      const route = mod.route ?? "—";
      return `| ${mod.name} | ${GROUP_LABELS[mod.group] ?? mod.group} | ${status} | ${enabledByDefault ? "yes" : "no"} | ${route} | ${perms} | ${reports} |`;
    });

  const requiredFieldsLines = Object.entries(profile.requiredFields)
    .map(([entity, fields]) => `- **${entity}**: ${fields.join(", ")}`)
    .join("\n");
  const workflowLines = profile.workflows.map((w) => `- ${w}`).join("\n");
  const setupTaskLines =
    setupTasks.length > 0
      ? setupTasks.map((t) => `- **${t.label}** — ${t.reason}`).join("\n")
      : "- (no dedicated setup tasks defined; uses common flow)";

  return `## ${bundle.icon} ${bundle.name} (\`${businessType}\`)

${bundle.description}

### Modules

| Module | Group | Status | Enabled by default | Route | Permissions | Reports |
|---|---|---|---|---|---|---|
${rows.join("\n")}

### Required fields

${requiredFieldsLines || "- (uses common profile)"}

### Workflows

${workflowLines}

### Setup tasks activated by this business type

${setupTaskLines}
`;
}

function main(): void {
  const businessTypes = Object.keys(BUSINESS_BUNDLES).filter((key) => key !== "custom");
  const sections = businessTypes.map(buildBusinessTypeSection).join("\n---\n\n");

  const header = `# Business-Pack Matrix (generated)

> **Auto-generated by \`npm run business:matrix\`** from \`src/shared/moduleRegistry.ts\`
> and \`src/modules/settings/service.ts\` (\`BUSINESS_CAPABILITY_PROFILES\`,
> \`BUSINESS_SETUP_TASKS\`, \`MODULE_PERMISSIONS\`, \`MODULE_REPORTS\`). Do not hand-edit —
> re-run the script after changing any of those files, and commit the diff.
>
> This is the "Developer view" matrix called for in \`FORWARD_PLAN.md\` Phase 3: for
> every business type, which modules it includes, what becomes required, which
> workflows activate, and which permissions/reports each module contributes.
>
> **Status column honesty note**: "Built and verified" is only used for core
> modules (proven by the retail end-to-end smoke path and each core module's own
> test suite). Every non-core module is labeled "Built but not verified" (has a
> dedicated frontend route, but this script cannot confirm live backend-test
> coverage — that still requires reading the module's own test file) or "Partial
> (no dedicated page)" (registry entry exists, no route wired yet) or "Not in this
> pack" (registry-known module, not part of this business type's default bundle).
> Only retail's core path (per \`FORWARD_PLAN.md\`) has passed a real end-to-end
> gate; treat every other status here as a starting point for investigation, not
> a completion claim.

`;

  writeFileSync(OUT_PATH, header + sections + "\n");
  console.log(`Wrote ${OUT_PATH}`);
}

main();
